# Generated by Django 3.1.2 on 2020-10-07 05:25

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Item',
            fields=[
                ('i_id', models.IntegerField(primary_key=True, serialize=False)),
                ('i_im_id', models.CharField(max_length=8, unique=True)),
                ('i_name', models.CharField(max_length=50)),
                ('i_price', models.DecimalField(decimal_places=2, max_digits=5)),
            ],
            options={
                'db_table': 'item',
            },
        ),
        migrations.CreateModel(
            name='Warehouse',
            fields=[
                ('w_id', models.IntegerField(primary_key=True, serialize=False)),
                ('w_name', models.CharField(max_length=50)),
                ('w_street', models.CharField(max_length=50)),
                ('w_city', models.CharField(max_length=50)),
                ('w_country', models.CharField(max_length=50)),
            ],
            options={
                'db_table': 'warehouse',
            },
        ),
        migrations.CreateModel(
            name='Stock',
            fields=[
                ('w', models.OneToOneField(on_delete=django.db.models.deletion.DO_NOTHING, primary_key=True, serialize=False, to='AppLine.warehouse')),
                ('s_qty', models.SmallIntegerField()),
                ('i', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='AppLine.item')),
            ],
            options={
                'db_table': 'stock',
                'unique_together': {('w', 'i')},
            },
        ),
    ]
